//! word list generated by parse_word_list.py
pub const ASS: [&str; 102] = [
    "@55",
    "@ssfcker",
    "@ssfucker",
    "@ssfvcker",
    "@sshole",
    "a_s_s",
    "ashole",
    "ass",
    "ass bandit",
    "ass eating boiolas",
    "ass eating nob jokeys",
    "ass fecker",
    "ass fuck",
    "ass fucker",
    "ass fucking boiolas",
    "ass fucking nob jokeys",
    "ass hole",
    "ass kisser",
    "ass licking",
    "ass muncher",
    "ass-bandit",
    "ass-fucker",
    "ass-fuckers",
    "ass-hole",
    "asses",
    "assface",
    "assfck",
    "assfcker",
    "assfk",
    "assfkcer",
    "assfker",
    "assfkr",
    "assfook",
    "assfuccer",
    "assfuck",
    "assfuck3r",
    "assfucker",
    "assfuckers",
    "assfuckerz",
    "assfukah",
    "assfukka",
    "assfukker",
    "assfukkerz",
    "assfvck3r",
    "assfvcker",
    "asshat",
    "asshol3",
    "asshole",
    "asshole fucker",
    "assholes",
    "assmunch",
    "assmuncher",
    "asswhole",
    "asswipe",
    "azz",
    "azzhole",
    "bitchass",
    "bitchasses",
    "bitchy ass",
    "cunt ass",
    "darkass",
    "dumasses",
    "dumb@ss",
    "dumbarrassed",
    "dumbass",
    "dumbass fucker",
    "dumbass mofoes",
    "dumbass mothafuckers",
    "dumbass son-of-a-bitch",
    "dumbasses",
    "fag asses",
    "fatass",
    "fatasses",
    "fuckass",
    "fuckasses",
    "fuckaz",
    "fucking asshole",
    "gay ass",
    "hoe-asses",
    "homo asses",
    "horse's asses",
    "jackass",
    "jackasses",
    "jackasss",
    "kiss ass",
    "kiss my ass",
    "markasses",
    "mofo ass",
    "mothafuckasses",
    "nigasses",
    "niggass",
    "punk ass mofoes",
    "punkasses",
    "queerasses",
    "shit-ass",
    "shitass",
    "shitasses",
    "shitassfucker",
    "shitassfuckface",
    "stupidasses",
    "tard asses",
    "wise ass",
];
pub const FUCK: [&str; 333] = [
    "@ssfcker",
    "@ssfucker",
    "@ssfvcker",
    "animal fucker",
    "arse-fucker",
    "arse-fuckers",
    "arsefuck",
    "arsefucker",
    "ass fecker",
    "ass fuck",
    "ass fucker",
    "ass fucking boiolas",
    "ass fucking nob jokeys",
    "ass-fucker",
    "ass-fuckers",
    "assfck",
    "assfcker",
    "assfk",
    "assfkcer",
    "assfker",
    "assfkr",
    "assfook",
    "assfuccer",
    "assfuck",
    "assfuck3r",
    "assfucker",
    "assfuckers",
    "assfuckerz",
    "assfukah",
    "assfukka",
    "assfukker",
    "assfukkerz",
    "assfvck3r",
    "assfvcker",
    "asshole fucker",
    "bitchfuck",
    "butt fuck",
    "butt fucker",
    "butt-fucker",
    "butt-fuckers",
    "butt-fucking-bandit",
    "buttfuck",
    "buttfucker",
    "buttfuckers",
    "closet fuckhead",
    "clusterfuck",
    "clusterfucked",
    "clusterfucker",
    "clusterfucking",
    "clusterfucks",
    "cyberfck",
    "cyberfcks",
    "cyberfuccs",
    "cyberfucks",
    "cyberfucs",
    "cyberfukk",
    "cyberfukks",
    "cyberfvcks",
    "dafuq",
    "darkfuck",
    "dick fucker",
    "dickfucker",
    "dog fuck",
    "dog fucker",
    "dog fucking",
    "dog-fucker",
    "dumb fucker",
    "dumbass fucker",
    "dumbfucks",
    "f_u_c_k",
    "f'ed",
    "f'er",
    "f@ck",
    "f@cker bunny",
    "f@k",
    "f0ck",
    "f0cked",
    "f0cker",
    "f0ckers",
    "face fuck",
    "fack",
    "fackuhs",
    "fart-fucker",
    "fccuker",
    "fck",
    "fck you",
    "fcka",
    "fckahz",
    "fcked",
    "fckedup",
    "fcker",
    "fckin",
    "fcking",
    "Fckk",
    "fckked",
    "fckking",
    "fcks",
    "fcktard",
    "fckyeah",
    "fcuk",
    "fcuked",
    "fcuker",
    "fcukers",
    "fcuking",
    "fcukker",
    "fcuks",
    "fcvking",
    "feck",
    "fecker",
    "fick",
    "finger fuck",
    "fk bunny",
    "fkbny",
    "fked",
    "fker",
    "fking",
    "fkings",
    "fkker",
    "focker",
    "fook",
    "fooker",
    "fookuh",
    "forked",
    "fuc",
    "fucc",
    "fucca",
    "fuccers",
    "fuccing",
    "fuccs",
    "Fuck",
    "fuck arse",
    "fuck face",
    "fuck faces",
    "fuck goblin",
    "fuck head",
    "fuck off",
    "fuck up",
    "fuck y0u",
    "fuck you",
    "fuck your",
    "fuck your mother",
    "fucka",
    "fuckahs",
    "fuckass",
    "fuckasses",
    "fuckaz",
    "fuckbag",
    "fuckboy",
    "fucked",
    "fucked up",
    "fuckem",
    "fucker",
    "fucker off",
    "fuckers",
    "fuckface",
    "fuckfaces",
    "fuckhead",
    "fuckheaded",
    "fuckheads",
    "fuckin",
    "fucking",
    "fucking A",
    "fucking asshole",
    "fucking bastard",
    "fucking hell",
    "fucking me",
    "fucking retard",
    "fucking shit",
    "fuckk",
    "fuckless",
    "fuckmachine",
    "fucknuckle",
    "fucks",
    "fuckshit",
    "fuckshitface",
    "fuckshithead",
    "fuckstar",
    "fuckster",
    "fuckstick",
    "fucktard",
    "fucktards",
    "fuckup",
    "fuckwad",
    "fuckwhore",
    "fucs",
    "fucx",
    "fudgefucker",
    "fudgepacking fucker",
    "fugged",
    "fugger",
    "fuggerz",
    "fuggings",
    "fugly",
    "fuk",
    "fuk1n",
    "fuk1ng",
    "fukcs",
    "fuker",
    "fukheads",
    "fukin",
    "fuking",
    "fukk",
    "fukka",
    "fukked",
    "fukker",
    "fukkers",
    "fukking",
    "fukkings",
    "fukkuh",
    "fuks",
    "fuku",
    "fukwhore",
    "fukwit",
    "fuq",
    "fux",
    "fux0r",
    "fvck",
    "fvck you",
    "fvcka",
    "fvckbunny",
    "fvcker",
    "fvckers",
    "fvckin",
    "fvcking",
    "fvckker bunny",
    "fvckwhi",
    "fxck",
    "fxcked",
    "fxcker",
    "fxcking",
    "gay fuck",
    "gay fucker",
    "get fucked",
    "go fuck yourself",
    "holy fuck",
    "jizzfucker",
    "p3nisfcker",
    "p3nisfcukers",
    "p3nisfvcker",
    "p3nisfvckers",
    "packingfudgefucker",
    "packingfudgefucking",
    "packsomefudgefucker",
    "penisfcker",
    "penisfuccer",
    "penisfucker",
    "penisfuckers",
    "penisfvcker",
    "penisfvckers",
    "phuc",
    "phucc",
    "phuccer",
    "phucchead",
    "phuccing",
    "phuck",
    "phuck3r",
    "phucked",
    "phucker",
    "phuckin",
    "phucking",
    "phuckings",
    "phucks",
    "phucup",
    "phuk",
    "phuked",
    "phukeds",
    "phukhead",
    "phuking",
    "phukings",
    "phukk",
    "phukked",
    "phukkeds",
    "phukker",
    "Phukking",
    "phuks",
    "phukshit",
    "phuku",
    "phukup",
    "phuq",
    "phuqs",
    "phvckings",
    "pig fucker",
    "pigfucker",
    "pigfuckers",
    "pigfucking",
    "pigfukker",
    "piggyfuck",
    "piss off fuckhead",
    "pussy fucker",
    "scamfuck",
    "scumfuck",
    "scumfucker",
    "scumfvck",
    "sh1tfuck",
    "shiesterfuck",
    "shiesterfuckface",
    "shiesterfuckhead",
    "shiesterfucks",
    "shit fuck",
    "shit fucker",
    "shit-fucker",
    "shitassfucker",
    "shitassfuckface",
    "shitefuck",
    "shitfacefuck",
    "shitfacefucker",
    "shitfck",
    "shitfk",
    "shitfuck",
    "shitfucker",
    "shitfuckhead",
    "shitfuckmotherfucker",
    "shitfucks",
    "shitfudgefucker",
    "shitfvck",
    "shitheadfucker",
    "shitheadfuckface",
    "shitsfuck",
    "shittasticfuck",
    "shitterfucker",
    "shittyfuck",
    "shittyfuckface",
    "shtfuk",
    "shut the fuck up",
    "shytfeisterfuck",
    "spicfuck",
    "stfu",
    "stupid fucker",
    "swine fucker",
    "tongue fucker",
    "tongue fucking",
    "useless fucker",
    "what the fuck",
];
pub const SEX: [&str; 2] = [
    "0ral seks",
    "0ral sex",
];
pub const ORGASM: [&str; 2] = [
    "0rg@sm",
    "0rgasms",
];
pub const EJACULATION: [&str; 1] = [
    "3jakulating",
];
pub const ARSE: [&str; 23] = [
    "4r5e",
    "4r5ed",
    "4r5es",
    "ar5e",
    "ar5ehole",
    "arse",
    "arse gobbler",
    "arse hole",
    "arse-bandit",
    "arse-bandits",
    "arse-fucker",
    "arse-fuckers",
    "arse-hole",
    "arse-shagger",
    "arsefuck",
    "arsefucker",
    "arsehole",
    "arseshit",
    "arsewipe",
    "feck arse",
    "fuck arse",
    "jackarse",
    "shit-arse",
];
pub const FORESKIN: [&str; 1] = [
    "4skin",
];
pub const SHIT: [&str; 165] = [
    "5h17",
    "5h1t",
    "ape shit",
    "ape shite",
    "apeshit",
    "apeshite",
    "arseshit",
    "batshit",
    "batshite",
    "bull shit",
    "bullshi",
    "bullshit",
    "bullshite",
    "caca",
    "cockshit",
    "darkshit",
    "dipsh1t",
    "dipsh1tty",
    "dipshat",
    "dipshidiot",
    "dipshit",
    "dipshite",
    "dipshits",
    "dipshitter",
    "dipshitty",
    "dog shit",
    "dogsh1t",
    "dogsh1ts",
    "dogshit",
    "dogshits",
    "dumbshit",
    "f@gshit",
    "fagshit",
    "fucking shit",
    "fuckshit",
    "fuckshitface",
    "fuckshithead",
    "fudgepackershitter",
    "full of shit",
    "g@yshit",
    "gay shit",
    "gobshite",
    "horse shit",
    "horseshit",
    "mofoshit",
    "motherfckshit",
    "motherfuckingshit",
    "phukshit",
    "pigshit",
    "piss shit",
    "s_h_i_",
    "s_h_i_s",
    "s/h/i/t",
    "sh! +",
    "sh!+",
    "sh1s",
    "sh1t",
    "sh1t3",
    "sh1td1ck",
    "sh1tdick",
    "sh1te",
    "sh1tfuck",
    "sh1th3ad",
    "sh1theads",
    "sh1ts",
    "sh1tsome",
    "sh1tt",
    "sh1tty",
    "shat",
    "sheeeet",
    "sheet",
    "sheister",
    "shet",
    "shi+",
    "shi+e",
    "shi+y",
    "shiat",
    "shiddick",
    "shiesterfuck",
    "shiesterfuckface",
    "shiesterfuckhead",
    "shiesterfucks",
    "shipdit",
    "shit",
    "shit face",
    "shit for brains",
    "shit fuck",
    "shit fucker",
    "shit head",
    "shit licker",
    "shit stain",
    "shit-arse",
    "shit-ass",
    "shit-bandit",
    "shit-fucker",
    "shit-stuffers",
    "shit3",
    "shitass",
    "shitasses",
    "shitassfucker",
    "shitassfuckface",
    "shitbag",
    "shitbird",
    "shitblimp",
    "shitblimps",
    "shitbrain",
    "shitd1ck",
    "shitdick",
    "shitdicks",
    "shitdikk",
    "shitdip",
    "shite",
    "shiteblimps",
    "shited",
    "shitedick",
    "shitefuck",
    "shitefulls",
    "shitehead",
    "shites",
    "shitey",
    "shitface",
    "shitfaced",
    "shitfacefuck",
    "shitfacefucker",
    "shitfck",
    "shitfk",
    "shitfreak",
    "shitfuck",
    "shitfucker",
    "shitfuckhead",
    "shitfuckmotherfucker",
    "shitfucks",
    "shitfudgefucker",
    "shitfvck",
    "shithead",
    "shitheadfucker",
    "shitheadfuckface",
    "shitheads",
    "shithole",
    "shits",
    "shitsdick",
    "shitsfuck",
    "shitsful",
    "shittastic",
    "shittasticfuck",
    "shitte",
    "shitted",
    "shitter",
    "shitterfucker",
    "shitti",
    "shitties",
    "shittiest",
    "shitting",
    "shittings",
    "shitty",
    "shitty mofoes",
    "shittydick",
    "shittydicks",
    "shittyfuck",
    "shittyfuckface",
    "shittyful",
    "shtfuk",
    "slanteyeshit",
    "spicshit",
    "towelshithead",
];
pub const SKANK: [&str; 8] = [
    "5kank",
    "sk@nks",
    "sk@nky",
    "sk@nkz",
    "skank",
    "skanks",
    "skanky",
    "skankz",
];
pub const ABRAHAM: [&str; 1] = [
    "abbie",
];
pub const ABEED: [&str; 1] = [
    "abeed",
];
pub const ABO: [&str; 1] = [
    "aboe",
];
pub const ANAL: [&str; 8] = [
    "anal",
    "anal hole",
    "anal hore",
    "anal pirate",
    "analingus",
    "analplug",
    "analplugs",
    "anilingus",
];
pub const ANUS: [&str; 2] = [
    "anus",
    "anus plug",
];
pub const APE: [&str; 4] = [
    "ape shit",
    "ape shite",
    "apeshit",
    "apeshite",
];
pub const BOIOLAS: [&str; 1] = [
    "ass fucking boiolas",
];
pub const KNOB: [&str; 47] = [
    "ass fucking nob jokeys",
    "cobb knobbler",
    "cock sucking nob jokeys",
    "faggot nob jokeys",
    "faggot nobjockies",
    "knob",
    "knob eater",
    "knob gobbler",
    "knob jockey",
    "knob-face",
    "knob-gobbler",
    "knob-head",
    "knob3d",
    "knob3nd",
    "knobd",
    "knobe",
    "knobead",
    "knobeads",
    "knobed",
    "knobeds",
    "knobend",
    "knobender",
    "knobends",
    "knobendy",
    "knobendz",
    "knober",
    "knobes",
    "knobgobbler",
    "knobhead",
    "knobheads",
    "knobjockies",
    "knobjocky",
    "knobjokey",
    "knobjokeys",
    "n0bhead",
    "n0bj0cky",
    "nob jockey",
    "nob jokeys",
    "nobbyhead",
    "nobhead",
    "nobheads",
    "nobj0key",
    "nobjockies",
    "nobjocky",
    "nobjokey",
    "nobjokeys",
    "nobs",
];
pub const WOUND: [&str; 1] = [
    "axe wound",
];
pub const BITCH: [&str; 85] = [
    "b to the inch",
    "b！tch",
    "b1+ch",
    "b17ch",
    "b1otch",
    "b1otchs",
    "b1tch",
    "b1tch1ng",
    "b1tch35",
    "b1tch3s",
    "b1tchees",
    "b1tches",
    "b1tchez",
    "b1tchin",
    "b1tching",
    "b1tchs",
    "b1tchy",
    "beeotch",
    "beyoch",
    "beyotch",
    "bi + ch",
    "bi+ch",
    "biatch",
    "biches",
    "biotch",
    "biotches",
    "biotchez",
    "bishes",
    "bitch",
    "bitch3s",
    "bitchass",
    "bitchasses",
    "bitched",
    "bitcher",
    "bitchers",
    "bitches",
    "bitchez",
    "bitchfuck",
    "bitchhole",
    "bitchin",
    "bitchin'",
    "bitching",
    "bitchlike",
    "bitchness",
    "bitchs",
    "bitchslap",
    "bitchtits",
    "bitchy",
    "bitchy ass",
    "bizzach",
    "crazy sob",
    "dumbass son-of-a-bitch",
    "faggot son-of-a-bitch",
    "g@y b1tch",
    "gay bitch",
    "goddamn son of a bitch",
    "goddamn son-of-a-bitch",
    "l3i + ch",
    "l3i+ch",
    "l3itch",
    "l3itches",
    "s.o.b.",
    "s.o.b.s",
    "slanteye b1tch",
    "soab",
    "son o bitch",
    "son of a bitch",
    "son-of-a-bitch",
    "sonna bitch",
    "sonofabitch",
    "sonofbitches",
    "sons of b1tches",
    "sons of bitches",
    "sons-of-bitches",
    "sonz of bitchez",
    "sum of a bitch",
    "sumbitch",
    "trashb1tch",
    "trashbitch",
    "trashbitches",
    "trashbitchez",
    "trashbtch",
    "trasherbitch",
    "trasherbitchs",
    "trashybitches",
];
pub const BOOBS: [&str; 3] = [
    "b00bz",
    "bewbs",
    "boobs",
];
pub const BOLLOCKS: [&str; 11] = [
    "b0llock",
    "b0llocks",
    "ballbag",
    "boll0ck",
    "bollock",
    "bollockchops",
    "bollocks",
    "bollocktician",
    "bollox",
    "dog's bollocks",
    "soppy bollucks",
];
pub const BABY_BATTER: [&str; 1] = [
    "baby batter",
];
pub const BANG: [&str; 1] = [
    "bangbros",
];
pub const BASTARD: [&str; 13] = [
    "bassturd",
    "bastard",
    "bastardish",
    "bastards",
    "basterd",
    "bastid",
    "bastinado",
    "basturd",
    "dumb bastard",
    "fucking bastard",
    "rat bastard",
    "rat baztad",
    "wankbastard",
];
pub const RETARD: [&str; 15] = [
    "bastard",
    "darktard",
    "fcktard",
    "fucking retard",
    "fucktard",
    "fucktards",
    "gaytard",
    "r3t@rd",
    "r3tard",
    "ragtard",
    "retard",
    "retardo",
    "retardotron",
    "slantard",
    "tard",
];
pub const MASTURBATE: [&str; 3] = [
    "bater",
    "bates",
    "m@asterbated",
];
pub const COCK: [&str; 77] = [
    "bbc",
    "bwc",
    "c0ck",
    "c0ckhead",
    "c0cks",
    "c0cksuccer",
    "c0cksucked",
    "c0cksucker",
    "c0cksuckers",
    "c0x",
    "c0xux0r",
    "caaak",
    "cack",
    "cawk",
    "cawk muncher",
    "cawkmuncher",
    "cawks",
    "cawksucker",
    "cock",
    "cock droplets",
    "cock head",
    "cock jockey",
    "cock knocker",
    "cock licker",
    "cock munch",
    "cock rider",
    "cock smoker",
    "cock snot",
    "cock suck",
    "cock sucker",
    "cock sucking",
    "cock sucking boiolas",
    "cock sucking nob jokeys",
    "cock tease",
    "cock-face",
    "cock-gobbler",
    "cock-head",
    "cock-sucker",
    "cock-suckers",
    "cockboy",
    "cockeater",
    "cockface",
    "cockgobbler",
    "cockh3ad",
    "cockhead",
    "cockheads",
    "cockhed",
    "cockless",
    "cocklicker",
    "cockmonger",
    "cockmunch",
    "cockmuncher",
    "cocks",
    "cockshit",
    "cockskin",
    "cocksmoker",
    "cocksucc",
    "cocksuccas",
    "cocksuccer",
    "cocksuccers",
    "cocksuck",
    "cocksuckas",
    "cocksucked",
    "cocksucker",
    "cocksuckers",
    "cocksucking",
    "cocksucking mothafuckers",
    "cocksucks",
    "cocksuk",
    "cocksuka",
    "cocksukka",
    "cocsuck",
    "cokmuncher",
    "coksucka",
    "cuksuker",
    "cuksukka",
    "suck my cock",
];
pub const BEAN_QUEEN: [&str; 1] = [
    "bean queen",
];
pub const BEANER: [&str; 2] = [
    "beaner",
    "beaners",
];
pub const MEAT: [&str; 5] = [
    "beat my meat",
    "beat the meat",
    "beat your meat",
    "man meat",
    "meat-sword",
];
pub const BEAT_OFF: [&str; 1] = [
    "beat off",
];
pub const BELLEND: [&str; 2] = [
    "bell end",
    "bellend",
];
pub const BENDER: [&str; 1] = [
    "bender",
];
pub const BLOWJOB: [&str; 3] = [
    "BJ",
    "blow job",
    "blowjob",
];
pub const BLACKY: [&str; 1] = [
    "blacky",
];
pub const BLOW_A_LOAD: [&str; 1] = [
    "blow a load",
];
pub const BLUMPKIN: [&str; 1] = [
    "blumpkin boy",
];
pub const BONDAGE: [&str; 1] = [
    "bondage",
];
pub const BONER: [&str; 1] = [
    "boner",
];
pub const BONK: [&str; 1] = [
    "bonk juice",
];
pub const BOOTY: [&str; 1] = [
    "booty",
];
pub const BREAST: [&str; 2] = [
    "breasticles",
    "breasts",
];
pub const BUGGER: [&str; 2] = [
    "bugger",
    "bugger off",
];
pub const BUM: [&str; 3] = [
    "bum-bandits",
    "bum-driller",
    "bumhole",
];
pub const BUNG: [&str; 1] = [
    "bung hole",
];
pub const BUTT: [&str; 13] = [
    "butt fuck",
    "butt fucker",
    "butt hole",
    "butt pirate",
    "butt-fucker",
    "butt-fuckers",
    "butt-fucking-bandit",
    "butt-munchers",
    "buttfuck",
    "buttfucker",
    "buttfuckers",
    "butthole",
    "butthole boy",
];
pub const BUTTERMILK: [&str; 1] = [
    "buttermilk",
];
pub const CUNT: [&str; 24] = [
    "c*nt",
    "c*ntface",
    "c*nts",
    "c*nty",
    "cunt",
    "cunt ass",
    "cunt fart",
    "cunt lick",
    "cunt licker",
    "cunt lips",
    "cuntasaurus rex",
    "cuntbag",
    "cuntbollock",
    "cuntelope",
    "cuntits",
    "cuntless",
    "cuntlick",
    "cuntlicker",
    "cuntlickers",
    "cuntness",
    "cunts",
    "cunty",
    "cuntz",
    "cuunt",
];
pub const COON: [&str; 9] = [
    "c00n",
    "c00nies",
    "coon",
    "coon1es",
    "cooni3s",
    "coonie",
    "coonies",
    "coons",
    "dune coon",
];
pub const COJONES: [&str; 2] = [
    "cagone",
    "cajones",
];
pub const CAMEL_JOCKEY: [&str; 1] = [
    "Camel jockey",
];
pub const CAMELTOE: [&str; 1] = [
    "cameltoe",
];
pub const CARPET_MUNCHER: [&str; 4] = [
    "carpet muncher",
    "carpetmuncher",
    "carpetmunchers",
    "carpetmunching",
];
pub const CHINK: [&str; 3] = [
    "ch1nk",
    "chink",
    "chinky",
];
pub const TESTICLES: [&str; 1] = [
    "chesticles",
];
pub const CHINA_VIRUS: [&str; 3] = [
    "china-virus",
    "chinavirus",
    "chinese-virus",
];
pub const CHINGCHONG: [&str; 1] = [
    "chingchong",
];
pub const CHOAD: [&str; 1] = [
    "choad nectar",
];
pub const CHOCHA: [&str; 1] = [
    "chocha",
];
pub const CHOKE_THE_CHICKEN: [&str; 1] = [
    "choke the chicken",
];
pub const CHOLO: [&str; 1] = [
    "cholo",
];
pub const CLIT: [&str; 2] = [
    "clitlickers",
    "klitoris",
];
pub const MOTHERFUCKER: [&str; 148] = [
    "cocksucking mothafuckers",
    "crazy mofos",
    "dumbass mofoes",
    "dumbass mothafuckers",
    "faggot mofoes",
    "faggot mothafuckers",
    "fothermuckers",
    "fuck your mother",
    "futhamucka",
    "goddamn mothafuckers",
    "m@derfaker",
    "m@derfuck",
    "m@derfuckers",
    "m0f0",
    "m0f0s",
    "m0fo",
    "m0foes",
    "m0fos",
    "m0thafucked",
    "m0thafucker",
    "m0thafucking",
    "m0therfuckeds",
    "m0therfucker",
    "m0therfucking",
    "m0therfvcker",
    "mf'er",
    "mf'ers",
    "mf'ing",
    "mfckers",
    "MFer",
    "MFers",
    "mfing",
    "mfk",
    "mfs",
    "mfukk",
    "mfukker",
    "mindfuck",
    "mof0es",
    "mof0s",
    "mofcker",
    "mofo",
    "mofo ass",
    "mofoes",
    "mofos",
    "mofoshit",
    "mofuccers",
    "mofucckers",
    "mofuck",
    "mofucker",
    "mofuckkas",
    "mofuk",
    "mofukkas",
    "motha fucka",
    "motha fucker",
    "motha fuckers",
    "mothaf@cked",
    "mothafcked",
    "mothafcking",
    "Mothafucc",
    "mothafucced",
    "mothafuccer",
    "mothafuccing",
    "mothafuck",
    "mothafucka",
    "mothafuckas",
    "mothafuckasses",
    "mothafuckaz",
    "mothafuckazzes",
    "mothafucked",
    "mothafuckeds",
    "mothafucker",
    "mothafuckers",
    "mothafuckin",
    "mothafucking",
    "mothafuckings",
    "mothafuckins",
    "mothafucks",
    "mothafuckz",
    "mothafvcked",
    "mother effer",
    "mother fuck",
    "mother fuck you",
    "mother fucka",
    "mother fucker",
    "mother fuckers",
    "mother fucking",
    "mothercker",
    "motherf@kka",
    "motherfacking",
    "motherfcked",
    "motherfckin",
    "motherfcking",
    "motherfcks",
    "motherfckshit",
    "motherfecka",
    "motherfecker",
    "motherfk",
    "motherfucca",
    "motherfuccas",
    "motherfuccers",
    "motherfuck",
    "motherfucked",
    "motherfuckeds",
    "motherfucker",
    "motherfuckers",
    "motherfuckin",
    "motherfucking",
    "motherfuckings",
    "motherfuckingshit",
    "motherfuckins",
    "motherfuckka",
    "motherfuckkas",
    "motherfuckkers",
    "motherfucks",
    "motherfukka",
    "motherfukker",
    "motherfukkings",
    "motherfvck",
    "motherfvcked",
    "motherfvckeds",
    "motherfvcker",
    "motherfvckers",
    "motherfvcking",
    "motherfxck",
    "motherfxcking",
    "mothfck",
    "mothter fuck",
    "mtherfuker",
    "mthrfcker",
    "muddafukkas",
    "mudderfuk",
    "mudderfukker",
    "muhfucking",
    "mutha fucka",
    "mutha fucker",
    "muthafecker",
    "muthafeckers",
    "muthafucka",
    "muthafuckers",
    "muthafuckings",
    "muthafuckker",
    "muthafuckkers",
    "muthafukka",
    "mutherfucker",
    "mutherfuckers",
    "punk ass mofoes",
    "shitfuckmotherfucker",
    "shitty mofoes",
];
pub const COOLIE: [&str; 1] = [
    "coolie",
];
pub const COOT: [&str; 5] = [
    "coot",
    "coot coot",
    "cooter",
    "cooter shooting",
    "cooterpuffing",
];
pub const COOTIES: [&str; 1] = [
    "cooties",
];
pub const COTTON_PICKER: [&str; 1] = [
    "cotton picker",
];
pub const CREAMPIE: [&str; 1] = [
    "creampie",
];
pub const CROTCH: [&str; 3] = [
    "crotch",
    "crotch fiddler",
    "crotchy",
];
pub const CROW: [&str; 2] = [
    "crow",
    "crows",
];
pub const CUM: [&str; 7] = [
    "cum goon",
    "cumball",
    "cumdumpster",
    "cumming",
    "cums",
    "cumslut",
    "cumz",
];
pub const CUNNILINGUS: [&str; 1] = [
    "cunnilingus",
];
pub const FART: [&str; 1] = [
    "cunt fart",
];
pub const TITS: [&str; 1] = [
    "cuntits",
];
pub const DICK: [&str; 56] = [
    "d!ck",
    "d!cks",
    "d1ck",
    "d1ckhead",
    "d1ckheads",
    "d1cks",
    "d1cksucker",
    "d1cksukka",
    "d1ckz",
    "dick breath",
    "dick face",
    "dick fucker",
    "dick head",
    "dick licker",
    "dick milker",
    "dick nibbler",
    "dick smoker",
    "dick sucker",
    "dick-face",
    "dick-gobbler",
    "dick-head",
    "dickface",
    "dickfucker",
    "dickhead",
    "dickheads",
    "dickjockies",
    "dickless",
    "dicklicker",
    "dickmuncher",
    "dicks",
    "dickskin",
    "dickslapper",
    "dicksmoker",
    "dicksucker",
    "dickvag",
    "dickz",
    "dikhead",
    "diks",
    "dix",
    "dlck",
    "dlcks",
    "double dick",
    "double dicking",
    "sh1td1ck",
    "sh1tdick",
    "shiddick",
    "shitd1ck",
    "shitdick",
    "shitdicks",
    "shitdikk",
    "shitedick",
    "shitsdick",
    "shittydick",
    "shittydicks",
    "suck my d",
    "suck my dick",
];
pub const DILDO: [&str; 4] = [
    "d!ld0",
    "d!ldo",
    "d1ldo",
    "dild0",
];
pub const DOGGY_STYLE: [&str; 6] = [
    "d0ggy style",
    "doggo style",
    "doggy style",
    "doggy_style",
    "dogie style",
    "dogstyle",
];
pub const DAGO: [&str; 1] = [
    "dago",
];
pub const DARKY: [&str; 4] = [
    "darkfuck",
    "darkie",
    "darktard",
    "darky",
];
pub const DIDDLE: [&str; 2] = [
    "diddle",
    "kid diddler",
];
pub const DIPSTICK: [&str; 1] = [
    "dipstick",
];
pub const DIRTY_SANCHEZ: [&str; 1] = [
    "dirty sanchez",
];
pub const DOLT: [&str; 1] = [
    "dolt",
];
pub const DONG: [&str; 2] = [
    "dong",
    "double-dong",
];
pub const DOUCHE: [&str; 5] = [
    "doosh",
    "douche",
    "douche bag",
    "douche canoe",
    "douchebag",
];
pub const DOTHEAD: [&str; 1] = [
    "dothead",
];
pub const DOUBLE_PEN: [&str; 1] = [
    "double pen",
];
pub const DUMP_A_LOAD: [&str; 1] = [
    "dump a load",
];
pub const DYKE: [&str; 1] = [
    "dyke",
];
pub const ERECTOPLASM: [&str; 1] = [
    "erectoplasm",
];
pub const FAGGOT: [&str; 36] = [
    "f@g",
    "f@gg0t",
    "f@gging",
    "f@ggot",
    "f@gs",
    "fag",
    "fag asses",
    "fag bag",
    "fag hag",
    "fag queen",
    "fag0t",
    "faget",
    "fagg0t",
    "fagging",
    "faggo",
    "faggot",
    "faggot mofoes",
    "faggot mothafuckers",
    "faggot nob jokeys",
    "faggot nobjockies",
    "faggot son-of-a-bitch",
    "faggoting",
    "faggots",
    "faggs",
    "faggy",
    "fagot",
    "fags",
    "fagshit",
    "feg",
    "mecha fag",
    "mega fag",
    "ph@ggots",
    "phaggot",
    "phaggots",
    "phagot",
    "phags",
];
pub const FAG: [&str; 1] = [
    "f@gshit",
];
pub const HAG: [&str; 1] = [
    "fag hag",
];
pub const FELLATIO: [&str; 2] = [
    "fellatio aficionado",
    "fellator",
];
pub const FINGER: [&str; 3] = [
    "finger",
    "fingerbanged",
    "fingerpop",
];
pub const FLAMER: [&str; 2] = [
    "flamer",
    "flamers",
];
pub const HELL: [&str; 2] = [
    "fucking hell",
    "go to hell",
];
pub const WHORE: [&str; 10] = [
    "fuckwhore",
    "fukwhore",
    "hoar",
    "wh0r3",
    "wh0re",
    "whoar",
    "whoars",
    "whor3",
    "whore",
    "whores",
];
pub const FUDGE_PACKER: [&str; 14] = [
    "fudgefucker",
    "fudgepacker",
    "fudgepackers",
    "fudgepackershitter",
    "fudgepacking fucker",
    "pack my fudge",
    "packerfudgehead",
    "packing fudge",
    "packing fudgehead",
    "packingfudge",
    "packingfudgefucker",
    "packingfudgefucking",
    "packsomefudgefucker",
    "shitfudgefucker",
];
pub const FUNBAGS: [&str; 1] = [
    "funbags",
];
pub const GAY: [&str; 15] = [
    "g@y b1tch",
    "g@ylord",
    "g@yshit",
    "gay ass",
    "gay bitch",
    "gay fuck",
    "gay fucker",
    "gay shit",
    "gay wad",
    "gayest",
    "gaylord",
    "gaylords",
    "gayness",
    "gaysian",
    "gaytard",
];
pub const DAMN: [&str; 20] = [
    "g0ddamn",
    "g0ddamned",
    "g0ddamnit",
    "god dammit",
    "god damn",
    "god damn it",
    "god damned",
    "god damnit",
    "god-dam",
    "god-damned",
    "godamnit",
    "godd@amn",
    "godd@mnit",
    "goddammit",
    "goddamn",
    "goddamn mothafuckers",
    "goddamn son of a bitch",
    "goddamn son-of-a-bitch",
    "goddamned",
    "goddamnit",
];
pub const GASH_STABBER: [&str; 1] = [
    "gash-stabber",
];
pub const GARBAGE_BAG: [&str; 1] = [
    "geebag",
];
pub const GIN_JOCKEY: [&str; 1] = [
    "gin jockey",
];
pub const GIRLYBOY: [&str; 2] = [
    "girlieboy",
    "girlyboy",
];
pub const GIRLY_BITS: [&str; 1] = [
    "girly bits",
];
pub const GOOK: [&str; 1] = [
    "gook",
];
pub const GOWL: [&str; 1] = [
    "gowl",
];
pub const GREASER: [&str; 1] = [
    "greaser",
];
pub const GROID: [&str; 1] = [
    "groid",
];
pub const GROPE: [&str; 1] = [
    "groper",
];
pub const GYPSY: [&str; 1] = [
    "gyp",
];
pub const HARRY_PALMS: [&str; 1] = [
    "harry palms",
];
pub const HEBE: [&str; 1] = [
    "heeb",
];
pub const NIGGER: [&str; 78] = [
    "higg@",
    "higg3r",
    "higga",
    "higger",
    "higgers",
    "jigga",
    "jigger",
    "jigro",
    "knickers",
    "n1ckker",
    "n1g3r",
    "n1g3rz",
    "n1gg@",
    "n1gg3r",
    "n1gg3rs",
    "n1gga",
    "n1ggah",
    "n1ggas",
    "n1ggazes",
    "n1gger",
    "n1ggers",
    "n1gguh",
    "negga",
    "neggar",
    "niccer",
    "nicka",
    "nickas",
    "nicker",
    "nickk3r",
    "nickker",
    "nig",
    "nig-nog",
    "niga",
    "nigah",
    "nigasses",
    "nigers",
    "nigg@",
    "nigg@hs",
    "nigg@s",
    "nigg@z",
    "nigg@zzes",
    "nigg3r",
    "nigg3rs",
    "nigg4h",
    "nigg4hs",
    "nigga",
    "nigga lover",
    "niggah",
    "niggahs",
    "niggahz",
    "niggas",
    "niggass",
    "niggaz",
    "niggazzes",
    "nigger",
    "nigger lover",
    "niggers",
    "niggerz",
    "niggir",
    "niggress",
    "nigguh",
    "nigguhs",
    "nigguhz",
    "niglet",
    "nignigs",
    "nignog",
    "nigra",
    "nigre",
    "nigs",
    "niguh",
    "nikk3r",
    "nikkas",
    "nikker",
    "nuckas",
    "nuggets",
    "sand nigger",
    "timber nigger",
    "wigger",
];
pub const HOE: [&str; 5] = [
    "hoe",
    "hoe-asses",
    "hoebag",
    "hoes",
    "stupid hoe",
];
pub const HOMOSEXUAL: [&str; 3] = [
    "homo",
    "homo asses",
    "homos",
];
pub const HOOTERS: [&str; 1] = [
    "hooters",
];
pub const HUSTLER: [&str; 1] = [
    "hustler",
];
pub const INJUN: [&str; 1] = [
    "injun",
];
pub const JERK_OFF: [&str; 11] = [
    "j-offs",
    "jerk off",
    "jerk-0ff",
    "jerk-0ffs",
    "jerk-off",
    "jerk-offs",
    "jerking off",
    "jerkoff",
    "jerkoff jerking off",
    "jerkoffs",
    "jerks off",
];
pub const JERK: [&str; 1] = [
    "j3rk",
];
pub const JAILBAIT: [&str; 4] = [
    "ja!lbait",
    "ja1lbait",
    "jailba!t",
    "jailbait",
];
pub const JACKOFF: [&str; 1] = [
    "Jack off",
];
pub const JACK_OFF: [&str; 6] = [
    "jack-off",
    "jack-offs",
    "jackoff",
    "jackoffs",
    "jackoffz",
    "jagoff",
];
pub const JAP: [&str; 1] = [
    "jap",
];
pub const JEW: [&str; 1] = [
    "jewboy",
];
pub const JIGGABOO: [&str; 14] = [
    "jigaboo",
    "jigaboos",
    "jigga",
    "jiggaboo",
    "jiggabooboo",
    "jiggaboos",
    "jiggabu",
    "jiggas",
    "jigger",
    "jiggerboo",
    "jiggerboos",
    "jiggs",
    "jiggyboo",
    "jigro",
];
pub const JIM_CROW: [&str; 1] = [
    "jim crow",
];
pub const JIZZ: [&str; 12] = [
    "jizz",
    "jizz eater",
    "jizz licker",
    "jizz-jockey",
    "jizzbags",
    "jizzed",
    "jizzes",
    "jizzfucker",
    "jizzing",
    "jizzsacks",
    "jizzstain",
    "jizzy",
];
pub const KIKE: [&str; 8] = [
    "k!k3",
    "k!ke",
    "k..!ke",
    "k1k3",
    "k1ke",
    "kike",
    "kikes",
    "kyke",
];
pub const KIDTOUCHER: [&str; 1] = [
    "kiddy touch",
];
pub const KITTY_PUNCHER: [&str; 1] = [
    "kitty puncher",
];
pub const KKK: [&str; 1] = [
    "kkk",
];
pub const KLAN: [&str; 1] = [
    "klan",
];
pub const NEGRO: [&str; 6] = [
    "kneegrows",
    "n3gro",
    "negr0",
    "negro",
    "negroes",
    "negroid",
];
pub const KU_KLUXER: [&str; 1] = [
    "ku kluxer",
];
pub const LADYBOY: [&str; 12] = [
    "l@dyb0i",
    "l@dyb0y",
    "l@dyboy",
    "ladboys",
    "ladboyz",
    "ladiboy",
    "lady-boy",
    "ladyb0i",
    "ladyb0y",
    "ladyboy",
    "ladyboys",
    "ladyboyz",
];
pub const LESBIAN: [&str; 1] = [
    "lesbo",
];
pub const LOOSE: [&str; 1] = [
    "loose woman",
];
pub const MONGOLOID: [&str; 3] = [
    "m0ng0l0id",
    "m0ngoloid",
    "mongoloid",
];
pub const MAN_CHOWDER: [&str; 1] = [
    "man chowder",
];
pub const MAN_SEED: [&str; 1] = [
    "man seed",
];
pub const MEAT_CURTAINS: [&str; 1] = [
    "meat curtains",
];
pub const MILF: [&str; 1] = [
    "milf",
];
pub const MOLEST: [&str; 1] = [
    "molester",
];
pub const MONG: [&str; 1] = [
    "mong",
];
pub const MONGREL: [&str; 1] = [
    "mongrel",
];
pub const MUFF: [&str; 7] = [
    "mufdive",
    "mufdivin",
    "muff",
    "muffdiving",
    "muffdivings",
    "muffindivin",
    "muffindiving",
];
pub const MUSHROOM_TIP: [&str; 1] = [
    "mushroom tip",
];
pub const NIGGGER: [&str; 1] = [
    "n1gg@hs",
];
pub const NIGGERS: [&str; 1] = [
    "n1ggahs",
];
pub const NIGGA: [&str; 1] = [
    "nigre",
];
pub const NIPPLE: [&str; 1] = [
    "nip",
];
pub const NONCE: [&str; 1] = [
    "nonce",
];
pub const NUT_BUTTER: [&str; 1] = [
    "nut butter",
];
pub const NUTSACK: [&str; 2] = [
    "nutsack",
    "nutsacks",
];
pub const NYMPH: [&str; 2] = [
    "nympho",
    "nymphomaniac",
];
pub const PUSSY: [&str; 20] = [
    "octopussy",
    "pu$sy",
    "pu55y",
    "puss",
    "pusses",
    "pussie",
    "pussies",
    "pussless",
    "pusslicker",
    "pussy",
    "pussy cat",
    "pussy lick",
    "pussy licker",
    "pussy licking",
    "pussylickers",
    "pussys",
    "pussywhipped",
    "puussy",
    "puzzies",
    "puzzy",
];
pub const OVEN_DODGER: [&str; 1] = [
    "oven dodger",
];
pub const PENIS: [&str; 14] = [
    "p3n1shead",
    "p3nisfcker",
    "p3nisfcukers",
    "p3nisfvcker",
    "p3nisfvckers",
    "peen",
    "peener",
    "penisfcker",
    "penisfuccer",
    "penisfucker",
    "penisfuckers",
    "penisfvcker",
    "penisfvckers",
    "penishead",
];
pub const PAKI: [&str; 1] = [
    "paki",
];
pub const PALM_JOCKEY: [&str; 1] = [
    "palm jockey",
];
pub const PANCAKE_FACE: [&str; 1] = [
    "pancake face",
];
pub const PECKER: [&str; 2] = [
    "pecker",
    "peckerhead",
];
pub const PEDOPHILE: [&str; 6] = [
    "pedo",
    "pedobear",
    "pedobears",
    "pedophl",
    "pedos",
    "pedoz",
];
pub const PETER_PUFFER: [&str; 2] = [
    "peter",
    "peter puffer",
];
pub const PIG: [&str; 7] = [
    "pig fucker",
    "pigfucker",
    "pigfuckers",
    "pigfucking",
    "pigfukker",
    "piggyfuck",
    "pigshit",
];
pub const PILLOW_BITER: [&str; 2] = [
    "pillow biter",
    "pillow-biter",
];
pub const PISS: [&str; 4] = [
    "piss face",
    "piss shit",
    "pissoff",
    "pissoffs",
];
pub const POLE_LICKER: [&str; 1] = [
    "pole licker",
];
pub const POLE_SMOKER: [&str; 1] = [
    "pole smoker",
];
pub const POLE_SUCKER: [&str; 1] = [
    "pole sucker",
];
pub const POLESMOKER: [&str; 1] = [
    "polesmoker",
];
pub const PORCH_MONKEY: [&str; 1] = [
    "porch monkey",
];
pub const PRICK: [&str; 5] = [
    "prick",
    "prick-face",
    "prick-gobbler",
    "prick-head",
    "pricks",
];
pub const PULL_THE_PUD: [&str; 1] = [
    "pull the pud",
];
pub const PUNANI: [&str; 1] = [
    "punani",
];
pub const PUNTA: [&str; 1] = [
    "puta",
];
pub const QUEER: [&str; 2] = [
    "queerasses",
    "queers",
];
pub const RETARDED: [&str; 1] = [
    "r3t@rded",
];
pub const RAGHEAD: [&str; 3] = [
    "raghead",
    "ragheads",
    "ragtard",
];
pub const RAMROD: [&str; 1] = [
    "ramrod",
];
pub const REACHAROUND: [&str; 1] = [
    "reacharound",
];
pub const RECTUM: [&str; 1] = [
    "rectum",
];
pub const REDSKIN: [&str; 1] = [
    "redskin",
];
pub const MONKEY: [&str; 1] = [
    "rice monkey",
];
pub const RIM_JOB: [&str; 1] = [
    "rim job",
];
pub const SLUT: [&str; 5] = [
    "s-lut",
    "slut",
    "slut hole",
    "sluts",
    "slutty",
];
pub const SADOMASOCHISM: [&str; 1] = [
    "S&M",
];
pub const BALLSACK: [&str; 1] = [
    "sack",
];
pub const SALAD_TOSSER: [&str; 1] = [
    "salad tosser",
];
pub const SAMBO: [&str; 1] = [
    "sambo",
];
pub const SAUSAGE_JOCKEY: [&str; 1] = [
    "sausage jockey",
];
pub const SCHLONG: [&str; 1] = [
    "schlong",
];
pub const SCUM: [&str; 4] = [
    "scumfuck",
    "scumfucker",
    "scumfvck",
    "scummy",
];
pub const SCUT: [&str; 1] = [
    "scut",
];
pub const SHEMALE: [&str; 7] = [
    "sh3mal3",
    "sh3male",
    "she-male",
    "shemal3",
    "shemale",
    "shemales",
    "shmale",
];
pub const SHIESTER: [&str; 1] = [
    "shiester",
];
pub const SHLONG: [&str; 1] = [
    "shlong",
];
pub const SHYLOCK: [&str; 1] = [
    "shylock",
];
pub const SISSY: [&str; 1] = [
    "sissy",
];
pub const SLANT_EYE: [&str; 8] = [
    "sl@nteye",
    "slantard",
    "slanteye",
    "slanteye b1tch",
    "slanteyes",
    "slanteyeshit",
    "slantfreak",
    "slanty",
];
pub const SLAG: [&str; 1] = [
    "slag",
];
pub const SLIT: [&str; 1] = [
    "slit",
];
pub const SNATCH: [&str; 2] = [
    "snatch",
    "snatch licker",
];
pub const SPANK: [&str; 1] = [
    "spanking",
];
pub const SPERM: [&str; 1] = [
    "sperm",
];
pub const SPHINCTER: [&str; 1] = [
    "sphincter",
];
pub const SPIC: [&str; 8] = [
    "spic",
    "spicfuck",
    "spick",
    "spics",
    "spicshit",
    "spig",
    "spik",
    "spix",
];
pub const SPOOK: [&str; 2] = [
    "spook",
    "spooks",
];
pub const SPUNK: [&str; 1] = [
    "spunk",
];
pub const STUMP_CHEWER: [&str; 1] = [
    "stump chewer",
];
pub const SUCK: [&str; 2] = [
    "suck",
    "suck off",
];
pub const SWINE: [&str; 2] = [
    "swine",
    "swine fucker",
];
pub const TACOHEAD: [&str; 1] = [
    "tacohead",
];
pub const TADGER: [&str; 1] = [
    "tadger",
];
pub const TAKING_THE_PISS: [&str; 1] = [
    "taking the piss",
];
pub const TALLYWACKER: [&str; 1] = [
    "tallywacker",
];
pub const TAR_BABY: [&str; 1] = [
    "tar-baby",
];
pub const TART: [&str; 1] = [
    "tart",
];
pub const THROAT_YOGURT: [&str; 1] = [
    "throat yogurt",
];
pub const THROATER: [&str; 1] = [
    "throater",
];
pub const TICKLE_THE_PICKLE: [&str; 1] = [
    "tickle the pickle",
];
pub const TIT: [&str; 1] = [
    "tits",
];
pub const TOSSER: [&str; 1] = [
    "tosser",
];
pub const TOSSING_SALAD: [&str; 1] = [
    "tossing salad",
];
pub const TOWELHEAD: [&str; 3] = [
    "towelhead",
    "towelheads",
    "towelshithead",
];
pub const TRAMP: [&str; 1] = [
    "tramp",
];
pub const TRANNY: [&str; 1] = [
    "Tranny",
];
pub const TRANSVESTITE: [&str; 1] = [
    "transvestite",
];
pub const TRASH: [&str; 7] = [
    "trashb1tch",
    "trashbitch",
    "trashbitches",
    "trashbitchez",
    "trashbtch",
    "trasherbitch",
    "trasherbitchs",
];
pub const TROUSER_SNAKE: [&str; 1] = [
    "trouser snake",
];
pub const TROUSERSNAKE: [&str; 1] = [
    "trousersnake",
];
pub const TURD: [&str; 2] = [
    "turdcutter",
    "turdhead",
];
pub const TWAT: [&str; 9] = [
    "tw@t",
    "twa+",
    "twat",
    "twat waffle",
    "twatface",
    "twats",
    "twatt",
    "twattish",
    "twatzilla",
];
pub const TWINK: [&str; 1] = [
    "twink",
];
pub const UPSKIRT: [&str; 1] = [
    "upskirts",
];
pub const VAGINA: [&str; 2] = [
    "vag",
    "vajayjay",
];
pub const VULVA: [&str; 1] = [
    "vulva",
];
pub const WANK: [&str; 16] = [
    "w@nker",
    "w@nkers",
    "w4nk3r",
    "w4nker",
    "wank",
    "wank off",
    "wank3r",
    "wank3rs",
    "wankbastard",
    "wanked",
    "wanker",
    "wankers",
    "wankies",
    "wanking",
    "wanks",
    "wnker",
];
pub const WANG: [&str; 2] = [
    "wang",
    "wang wrangler",
];
pub const WETBACK: [&str; 4] = [
    "we1back",
    "wet back",
    "wetback",
    "wetbacks",
];
pub const WEENIE: [&str; 1] = [
    "weenie",
];
pub const WEINER: [&str; 1] = [
    "weiner",
];
pub const WHACK_OFF: [&str; 1] = [
    "whack off",
];
pub const WILLY_WHACKER: [&str; 1] = [
    "willy-whacker",
];
pub const WINDOW_LICKER: [&str; 1] = [
    "window licker",
];
pub const WOP: [&str; 2] = [
    "wop",
    "wophead",
];
pub const ZIPPERHEAD: [&str; 2] = [
    "zip in the wire",
    "zipperhead",
];
